/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fash.example.kafkav.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TruckCoordinates extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 547600102382990854L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TruckCoordinates\",\"namespace\":\"com.fash.example.kafkav.avro\",\"fields\":[{\"name\":\"ID\",\"type\":\"int\"},{\"name\":\"Latitude\",\"type\":\"string\"},{\"name\":\"Longitude\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TruckCoordinates> ENCODER =
      new BinaryMessageEncoder<TruckCoordinates>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TruckCoordinates> DECODER =
      new BinaryMessageDecoder<TruckCoordinates>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TruckCoordinates> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TruckCoordinates> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TruckCoordinates> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TruckCoordinates>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TruckCoordinates to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TruckCoordinates from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TruckCoordinates instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TruckCoordinates fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int ID;
   private java.lang.CharSequence Latitude;
   private java.lang.CharSequence Longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TruckCoordinates() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   * @param Latitude The new value for Latitude
   * @param Longitude The new value for Longitude
   */
  public TruckCoordinates(java.lang.Integer ID, java.lang.CharSequence Latitude, java.lang.CharSequence Longitude) {
    this.ID = ID;
    this.Latitude = Latitude;
    this.Longitude = Longitude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return Latitude;
    case 2: return Longitude;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.Integer)value$; break;
    case 1: Latitude = (java.lang.CharSequence)value$; break;
    case 2: Longitude = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public int getID() {
    return ID;
  }


  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(int value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'Latitude' field.
   * @return The value of the 'Latitude' field.
   */
  public java.lang.CharSequence getLatitude() {
    return Latitude;
  }


  /**
   * Sets the value of the 'Latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.Latitude = value;
  }

  /**
   * Gets the value of the 'Longitude' field.
   * @return The value of the 'Longitude' field.
   */
  public java.lang.CharSequence getLongitude() {
    return Longitude;
  }


  /**
   * Sets the value of the 'Longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.Longitude = value;
  }

  /**
   * Creates a new TruckCoordinates RecordBuilder.
   * @return A new TruckCoordinates RecordBuilder
   */
  public static com.fash.example.kafkav.avro.TruckCoordinates.Builder newBuilder() {
    return new com.fash.example.kafkav.avro.TruckCoordinates.Builder();
  }

  /**
   * Creates a new TruckCoordinates RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TruckCoordinates RecordBuilder
   */
  public static com.fash.example.kafkav.avro.TruckCoordinates.Builder newBuilder(com.fash.example.kafkav.avro.TruckCoordinates.Builder other) {
    if (other == null) {
      return new com.fash.example.kafkav.avro.TruckCoordinates.Builder();
    } else {
      return new com.fash.example.kafkav.avro.TruckCoordinates.Builder(other);
    }
  }

  /**
   * Creates a new TruckCoordinates RecordBuilder by copying an existing TruckCoordinates instance.
   * @param other The existing instance to copy.
   * @return A new TruckCoordinates RecordBuilder
   */
  public static com.fash.example.kafkav.avro.TruckCoordinates.Builder newBuilder(com.fash.example.kafkav.avro.TruckCoordinates other) {
    if (other == null) {
      return new com.fash.example.kafkav.avro.TruckCoordinates.Builder();
    } else {
      return new com.fash.example.kafkav.avro.TruckCoordinates.Builder(other);
    }
  }

  /**
   * RecordBuilder for TruckCoordinates instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TruckCoordinates>
    implements org.apache.avro.data.RecordBuilder<TruckCoordinates> {

    private int ID;
    private java.lang.CharSequence Latitude;
    private java.lang.CharSequence Longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fash.example.kafkav.avro.TruckCoordinates.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Latitude)) {
        this.Latitude = data().deepCopy(fields()[1].schema(), other.Latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Longitude)) {
        this.Longitude = data().deepCopy(fields()[2].schema(), other.Longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TruckCoordinates instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fash.example.kafkav.avro.TruckCoordinates other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Latitude)) {
        this.Latitude = data().deepCopy(fields()[1].schema(), other.Latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Longitude)) {
        this.Longitude = data().deepCopy(fields()[2].schema(), other.Longitude);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public int getID() {
      return ID;
    }


    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder setID(int value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder clearID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return Latitude;
    }


    /**
      * Sets the value of the 'Latitude' field.
      * @param value The value of 'Latitude'.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Latitude' field has been set.
      * @return True if the 'Latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Latitude' field.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder clearLatitude() {
      Latitude = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return Longitude;
    }


    /**
      * Sets the value of the 'Longitude' field.
      * @param value The value of 'Longitude'.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Longitude' field has been set.
      * @return True if the 'Longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Longitude' field.
      * @return This builder.
      */
    public com.fash.example.kafkav.avro.TruckCoordinates.Builder clearLongitude() {
      Longitude = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TruckCoordinates build() {
      try {
        TruckCoordinates record = new TruckCoordinates();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.Integer) defaultValue(fields()[0]);
        record.Latitude = fieldSetFlags()[1] ? this.Latitude : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Longitude = fieldSetFlags()[2] ? this.Longitude : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TruckCoordinates>
    WRITER$ = (org.apache.avro.io.DatumWriter<TruckCoordinates>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TruckCoordinates>
    READER$ = (org.apache.avro.io.DatumReader<TruckCoordinates>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.ID);

    out.writeString(this.Latitude);

    out.writeString(this.Longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID = in.readInt();

      this.Latitude = in.readString(this.Latitude instanceof Utf8 ? (Utf8)this.Latitude : null);

      this.Longitude = in.readString(this.Longitude instanceof Utf8 ? (Utf8)this.Longitude : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID = in.readInt();
          break;

        case 1:
          this.Latitude = in.readString(this.Latitude instanceof Utf8 ? (Utf8)this.Latitude : null);
          break;

        case 2:
          this.Longitude = in.readString(this.Longitude instanceof Utf8 ? (Utf8)this.Longitude : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










